name: Build and Publish Image
on:
    push:
      branches: [ "main" ]
      paths:
          - Dockerfile
          - requirements.txt
    workflow_dispatch:

env:
    REGISTRY_USER: ${{ github.actor }}
    REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
     contents: read
     packages: write

    steps:
     - name: Checkout repository
       uses: actions/checkout@v4

     - name: Build the Docker image
       run: docker image build -f Dockerfile --tag ghcr.io/kbdharun/ml-lab-image:latest .

     - name: Push To GHCR
       run: |
         docker login ghcr.io -u ${{ env.REGISTRY_USER }} -p ${{ env.REGISTRY_PASSWORD }}
         docker image push "ghcr.io/kbdharun/ml-lab-image:latest"

     - uses: sigstore/cosign-installer@v3.5.0
     - name: Sign container image
       run: |
         cosign sign -y --key env://COSIGN_PRIVATE_KEY ghcr.io/kbdharun/ml-lab-image:latest
       env:
          COSIGN_EXPERIMENTAL: false
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
